#!/bin/bash

CONFIG="/etc/vortigaunt/vortigaunt.conf"

if [ -f "$CONFIG" ]; then
    source "$CONFIG"
else
    echo "Configuración no encontrada"
    exit 1
fi

BASE="$VORTIGAUNT_HOME"
FILE="$BASE/database/identity.md"

echo "=========================="
echo "     VORTIGAUNT ABOUT"
echo "=========================="
echo

cat "$FILE"

echo
echo "=========================="
echo " VORTIGAUNT ONLINE"
echo "=========================="
